### ISSUE TITLE
apply scc command is incorrect

### ISSUE THREAD

**Issue by RocketsFang** [IBM/cloud-pak#100]
when using the command list in open shift markdown file to create SCC resources,  i met this error:
[rockets@openshift1 scc]# oc apply -f --validate=false .
error: Unexpected args: [.]
See 'oc apply -h' for help and examples.

after modify command like this - oc apply -f --validate=false .     it's passed

**Comment by cdjohnson** [comment]
Thanks for the issue.  Fixed
